apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: BIND_HOST
          valueFrom:
            configMapKeyRef:
              key: BIND_HOST
              name: docker-vue-storefront-default-env
        - name: NODE_CONFIG_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_CONFIG_ENV
              name: docker-vue-storefront-default-env
        - name: PM2_ARGS
          valueFrom:
            configMapKeyRef:
              key: PM2_ARGS
              name: docker-vue-storefront-default-env
        - name: VS_ENV
          valueFrom:
            configMapKeyRef:
              key: VS_ENV
              name: docker-vue-storefront-default-env
        image: revnite/vue-storefront-app
        imagePullPolicy: ""
        name: vue-storefront-app
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /var/www/dist
          name: app-tmpfs0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - emptyDir:
          medium: Memory
        name: app-tmpfs0
status: {}
